### ISSUE TITLE
Wekan.sh enable email invitations and other issues

### ISSUE THREAD

**Issue by ghost** [j8r/DPlatform#16]
Hi, i just want to share something that i've discovered using that app with docker,  when creating the systemd unit you could ask the user to set a smtp server to send email, and then add that strings to the unit:
`Environment=MAIL_URL=smtp://user:password@smtpserverport:port/                                                                              
Environment=MAIL_FROM=emailaddress`

The other thing is the update script that i don't fully understand because:

at line 3:  `[ $1 = update ] && { systemctl stop wekan; rm -rf /home/wekan/bundle; }`

but at line 35 `mv bundle Wekan`

so when `$1=update` you are trying to delete `/home/wekan/bundle` which doesn't exist anymore, because at line 35 you've renamed bundle to Wekan. 

Thank you for creating all of this set of scripts, you saved me  a lot of time!

**Comment by j8r** [comment]
Thanks you too! You're right, I've done some changes. Now it will just be `/home/wekan/*`, the bundle content will be directly extracted to the current directory `/home/wekan`.
Anyway, DPlatform / systemd aren't designed for Docker, even if it works. Docker shouldn't need systemd because it run an app with parameters set in the Dockerfile when the container is launched. I plan to create a [DPlatform Docker project](https://github.com/DFabric/DPlatform-DockerShip).

**Comment by ghost** [comment]
The two environment variables are indipendent from docker, they belong to wekan, some time ago i've compiled wekan from source(on a x86 machine), and following their guide you need to export some variables [https://github.com/wekan/wekan/wiki/Install-and-Update#manual-installation-steps](url). 

So now in my raspbian, i went to `/etc/systemd/system/wekan.service` and added the two lines above (with my credentials) and email starts working. The drawback is that the password will be stored in plain text inside the unit.

**Comment by j8r** [comment]
Fixed. I haven't added the email environment variables asked with a message box, because it doesn't appears to be needed to have a working Wekan, finally that most people research.
