### ISSUE TITLE
Nextcloud 12

### ISSUE THREAD

**Issue by pixelyo** [j8r/DPlatform#42]
Is there an upgrade to Nextcloud 12 planned?

**Comment by j8r** [comment]
We use the [PHP  web installer script](https://download.nextcloud.com/server/installer/setup-nextcloud.php ) provided by Nextcloud for the setup.

We should ask to the Nextcloud team on their forum if they plan to update it.

I see `Nextcloud version define('NC_VERSION', '11.0.0');` in the script. Maybe juste changing 11 to 12 will do the trick for you?

For DPlaftorm, I prefer to wait for them to update the installer.

**Comment by siliconninja** [comment]
The Nextcloud team has recently merged an update to their web installer. It now installs version 12.0.1.
https://github.com/nextcloud/web-installer/pull/15

@pixelyo @j8r should we re-open this issue?

**Comment by j8r** [comment]
@siliconninja They haven't pushed yet this update yet on https://download.nextcloud.com/server/installer/setup-nextcloud.php, still on `11.0.0` since 2016-12-13.

On this pull request we see they change from `11.0.2` to `12.0.1`

So is it just an ovesight, or do they consider the script not ready?

We can end up to use this GitHub URL https://raw.githubusercontent.com/nextcloud/web-installer/master/setup-nextcloud.php, even if I prefer to use the official one.

**Comment by siliconninja** [comment]
I don't see anything on the forums (https://help.nextcloud.com/search?q=setup-nextcloud.php) related to this issue. I'm not sure whether it is an oversight or not ready for production. I have opened an issue on the https://github.com/nextcloud/web-installer repo (https://github.com/nextcloud/web-installer/issues/18).
