### ISSUE TITLE
New link to DFabric from FreshRSS?

### ISSUE THREAD

**Issue by Alkarex** [j8r/DPlatform#51]
Hello,
The DPlatform link from the FreshRSS readme https://github.com/FreshRSS/FreshRSS/pull/1159 is broken, so I am removing it. But you are welcome to send an update when transitioned to dppm.
* https://github.com/DFabric/DPlatform-Shell/blob/master/apps/FreshRSS.sh

**Comment by j8r** [comment]
No problem @Alkarex , you're welcome!
The main blocking issue is https://github.com/FreshRSS/FreshRSS/issues/1728 , because a mapping can't really be done on a PHP file. Modifying it programmatically is even harder.
The same problem applies for Wordpress and Nextcould, too bad. Don't know how to solve this problem cleanly.

That's why for now only https://github.com/SSilence/selfoss is supported. I will send a PR when DPPM will support FreshRSS.

**Comment by Alkarex** [comment]
@j8r What do you need to change manually in the configuration files? There is a CLI, which should be able to do that for you https://github.com/FreshRSS/FreshRSS/tree/dev/cli If any feature lacks, we can add it.

**Comment by j8r** [comment]
Didn't know this CLI.
For now on the dppm side, a `pkg.yml` describe a mapping, which is used to interact with the configuration file through an uniform API for all supported applications.

I think I will have no other choice for most PHP applications to end up creating a PHP subprocess each time I want to get/modify configurations. It would be a lot less efficient, but I see no other choice.

Thanks to point this out 😀
